### ISSUE TITLE
Non-Browser based Bot issue

### ISSUE THREAD

**Issue by yibo-liang** [xSke/Pxls#69]
Just wonder if you have considered there are a lot of non-browser based bot existing. Usually in NodeJS/Python/Java etc. Session cookies are obtained using selenium drivers and are used to create websocket directly to your server. All the effort I have seen from your commit is useless against such kind of bot. The best way I could think of is to frequently change {type:"place"} key word or server address http://host/ws to some random hard coded string in the backend, with some js encription in the frontend and delay of updating your code on Github so bot makers do not know. Also, increase captcha threshold will help but will not change anything, since botter just have to keep entering catpcha every other second (with 100+ accounts).

**Comment by Sorunome** [comment]
We have thought about this indeed and it seems like making the user tools more usable was a great step towards that - because now real people are actually able to ban the bots they detected.

Also, all this other protection you are talking about were actually ideas discussed by us but deemed not worthy of implementing as they can be avoided rather easily. Still thank you for your input!
